services:
  - type: web
    name: socialscannerweb
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG_MODE
        value: False
      - key: PYTHONUNBUFFERED
        value: true
      - key: SCHEDULER_API_ENABLED
        value: False
      - key: SCHEDULER_TRIGGER_HOUR
        value: 6
      - key: SCHEDULER_TRIGGER_MINUTE
        value: 0
      - key: DB_ENGINE
        value: postgresql
      - key: DB_HOST
        fromDatabase:
          name: socialscannerdb
          property: host
      - key: DB_NAME
        fromDatabase:
          name: socialscannerdb
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: socialscannerdb
          property: user
      - key: DB_PASS
        fromDatabase:
          name: socialscannerdb
          property: password
      - key: DB_PORT
        fromDatabase:
          name: socialscannerdb
          property: port

databases:
  - name: socialscannerdb
    databaseName: socialscannerdb
    plan: free
