"""followers

Revision ID: 23317857c085
Revises: 5c2a7464450b
Create Date: 2024-05-05 16:20:13.651812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23317857c085'
down_revision = '5c2a7464450b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('posts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.drop_column('posts')
        batch_op.drop_column('likes')
        batch_op.drop_column('followers')

    # ### end Alembic commands ###
