"""260424

Revision ID: 3157a52ef7c5
Revises: 933b63c8ee33
Create Date: 2024-04-26 23:29:25.949544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3157a52ef7c5'
down_revision = '933b63c8ee33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanresults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socialaccount_id', sa.Integer(), nullable=False),
    sa.Column('public_profile_name', sa.String(length=100), nullable=True),
    sa.Column('bio_text', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('posts', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('creation_time', sa.Time(), nullable=True),
    sa.Column('external_url', sa.String(length=255), nullable=True),
    sa.Column('time_taken', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['socialaccount_id'], ['socialaccounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scanlogs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanlogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_profile_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bio_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('posts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('creation_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('external_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time_taken', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('socialaccount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['socialaccount_id'], ['socialaccounts.id'], name='scanlogs_socialaccount_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scanlogs_pkey')
    )
    op.drop_table('scanresults')
    # ### end Alembic commands ###
