"""profilepicture3

Revision ID: 39cfd8f7e467
Revises: 490ec4075a9d
Create Date: 2024-04-02 23:13:35.196899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cfd8f7e467'
down_revision = '490ec4075a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(), nullable=True))
        batch_op.drop_column('profile_picture_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
