"""unique username_platform

Revision ID: 4491e0a1c3a2
Revises: 2637c67192d6
Create Date: 2024-06-15 16:30:43.683204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4491e0a1c3a2'
down_revision = '2637c67192d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.drop_constraint('socialaccounts_username_key', type_='unique')
        batch_op.create_unique_constraint('_username_platform_uc', ['username', 'platform_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.drop_constraint('_username_platform_uc', type_='unique')
        batch_op.create_unique_constraint('socialaccounts_username_key', ['username'])


    # ### end Alembic commands ###
