"""profilepicture2

Revision ID: 490ec4075a9d
Revises: 72f2ac43f7b6
Create Date: 2024-04-02 04:53:51.033169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490ec4075a9d'
down_revision = '72f2ac43f7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_link', sa.String(), nullable=True))
        batch_op.drop_column('default_profile_picture_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_profile_picture_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_picture_link')

    # ### end Alembic commands ###
