"""270422-3

Revision ID: 4a00d934f75a
Revises: cc6b3bd0912c
Create Date: 2024-04-27 20:04:30.958265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a00d934f75a'
down_revision = 'cc6b3bd0912c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('public_profile_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('external_url')
        batch_op.drop_column('public_profile_name')
        batch_op.drop_column('bio_text')

    # ### end Alembic commands ###
