"""init2

Revision ID: 4c56fc84dd30
Revises: cba232e2f6ea
Create Date: 2024-04-01 21:13:35.002691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c56fc84dd30'
down_revision = 'cba232e2f6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subprofiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subprofile_id', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.Date(), nullable=True),
    sa.Column('scan_time', sa.Time(), nullable=True),
    sa.Column('public_profile_name', sa.String(), nullable=True),
    sa.Column('bio_text', sa.Text(), nullable=True),
    sa.Column('profile_picture_link', sa.String(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('posts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subprofile_id'], ['subprofiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scanlogs')
    op.drop_table('subprofiles')
    op.drop_table('influencers')
    # ### end Alembic commands ###
