"""270422-5

Revision ID: 5c2a7464450b
Revises: cefedecd3f40
Create Date: 2024-04-27 21:40:00.139533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2a7464450b'
down_revision = 'cefedecd3f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.alter_column('name_english',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name_english'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name_english',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
