"""220424-4

Revision ID: 71e61a564637
Revises: 9aa7b7b25064
Create Date: 2024-04-22 00:40:05.608173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e61a564637'
down_revision = '9aa7b7b25064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('socialaccount_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('scanlogs_social_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'socialaccounts', ['socialaccount_id'], ['id'])
        batch_op.drop_column('social_account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scanlogs_social_account_id_fkey', 'socialaccounts', ['social_account_id'], ['id'])
        batch_op.drop_column('socialaccount_id')

    # ### end Alembic commands ###
