"""profilepicture

Revision ID: 72f2ac43f7b6
Revises: 4c56fc84dd30
Create Date: 2024-04-02 04:44:25.422855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f2ac43f7b6'
down_revision = '4c56fc84dd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_profile_picture_link', sa.String(), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('subprofiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_link', sa.String(), nullable=True))
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subprofiles', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('profile_picture_link')

    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('default_profile_picture_link')

    # ### end Alembic commands ###
