"""270422

Revision ID: 7806f47294d7
Revises: f5f4e17728ba
Create Date: 2024-04-27 06:20:28.470998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7806f47294d7'
down_revision = 'f5f4e17728ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlog', schema=None) as batch_op:
        batch_op.alter_column(
            "success_count",
            existing_type=sa.VARCHAR(length=255),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
            postgresql_using="success_count::jsonb")
        batch_op.alter_column(
            "failure_count",
            existing_type=sa.VARCHAR(length=255),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
            postgresql_using="failure_count::jsonb")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlog', schema=None) as batch_op:
        batch_op.alter_column('failure_count',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('success_count',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
