"""socialaccount2

Revision ID: 7db5d7139a8c
Revises: 82cea1a34686
Create Date: 2024-04-03 03:03:54.302211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db5d7139a8c'
down_revision = '82cea1a34686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socialaccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('subprofiles')
    op.execute("DROP TABLE IF EXISTS subprofiles CASCADE")
    with op.batch_alter_table('scanlogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('socialaccount_id', sa.Integer(), nullable=False))
        # batch_op.drop_constraint('scanlogs_subprofile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'socialaccounts', ['socialaccount_id'], ['id'])
        batch_op.drop_column('subprofile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subprofile_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scanlogs_subprofile_id_fkey', 'subprofiles', ['subprofile_id'], ['id'])
        batch_op.drop_column('socialaccount_id')

    op.create_table('subprofiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('influencer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], name='subprofiles_influencer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subprofiles_pkey')
    )
    op.drop_table('socialaccounts')
    # ### end Alembic commands ###
