"""170424-2

Revision ID: 939c5f9a4c6f
Revises: 5eebf58f7d28
Create Date: 2024-04-17 02:31:43.049856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939c5f9a4c6f'
down_revision = '5eebf58f7d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ip', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('user_ip')

    # ### end Alembic commands ###
