"""190424

Revision ID: a22b72a72853
Revises: 939c5f9a4c6f
Create Date: 2024-04-19 23:45:00.881481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22b72a72853'
down_revision = '939c5f9a4c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('time_taken', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlogs', schema=None) as batch_op:
        batch_op.drop_column('time_taken')
        batch_op.drop_column('external_url')

    # ### end Alembic commands ###
