"""contents

Revision ID: b794f861d6a7
Revises: 2ee9443588db
Create Date: 2024-04-12 04:36:53.689657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b794f861d6a7'
down_revision = '2ee9443588db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socialaccount_content',
    sa.Column('socialaccount_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['socialaccount_id'], ['socialaccounts.id'], ),
    sa.PrimaryKeyConstraint('socialaccount_id', 'content_id')
    )
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.drop_constraint('socialaccounts_content_id_fkey', type_='foreignkey')
        batch_op.drop_column('content_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('socialaccounts_content_id_fkey', 'contents', ['content_id'], ['id'])

    op.drop_table('socialaccount_content')
    # ### end Alembic commands ###
