"""190424-2

Revision ID: bf9824148d62
Revises: a22b72a72853
Create Date: 2024-04-20 00:03:43.054167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9824148d62'
down_revision = 'a22b72a72853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlogs', schema=None) as batch_op:
        batch_op.alter_column('time_taken',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlogs', schema=None) as batch_op:
        batch_op.alter_column('time_taken',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
