"""270422-2

Revision ID: cc6b3bd0912c
Revises: 7806f47294d7
Create Date: 2024-04-27 18:53:06.953252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc6b3bd0912c'
down_revision = '7806f47294d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlog', schema=None) as batch_op:
        batch_op.alter_column('failures',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
                postgresql_using="failure_count::jsonb")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanlog', schema=None) as batch_op:
        batch_op.alter_column('failures',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
