"""260422

Revision ID: f5f4e17728ba
Revises: 3157a52ef7c5
Create Date: 2024-04-27 00:19:41.662318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f4e17728ba'
down_revision = '3157a52ef7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.String(length=255), nullable=True),
    sa.Column('failure_count', sa.String(length=255), nullable=True),
    sa.Column('failures', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('creation_time', sa.Time(), nullable=True),
    sa.Column('time_taken', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scanlog')
    # ### end Alembic commands ###
